name: hello-dubbo-entity
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: rdc-snapshots
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        env:
          MAVEN_USER_NAME: ${{ secrets.MAVEN_USER_NAME }}
          MAVEN_USER_PASSWORD: ${{ secrets.MAVEN_USER_PASSWORD }}
          DOCKER_USER_NAME: ${{ secrets.DOCKERUSER_NAME }}
          DOCKER_USER_PASSWORD: ${{ secrets.DOCKER_USER_PASSWORD }}
        run: |
          echo ${DOCKER_USER_NAME}
          echo ${DOCKER_USER_PASSWORD}
          docker login --username=${DOCKER_USER_NAME} --password=${DOCKER_USER_PASSWORD} registry.cn-qingdao.aliyuncs.com

